cli:
  build: misc/docker/php
  volumes_from:
    - data
  links:
    - web:piwik.dev
    - db

web:
  build: misc/docker/nginx
#  ports:
#    - "8080:80"
  volumes_from:
    - data
  links:
    - phpfpm

phpfpm:
  build: misc/docker/phpfpm
  command: php5-fpm
  expose:
    - "9000"
  volumes_from:
    - data
  links:
    - db

db:
  image: mysql
  volumes_from:
    # necessary for LOAD DATA INFILE
    - data
  environment:
    - MYSQL_DATABASE=piwik
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_USER=piwik
    - MYSQL_PASSWORD=
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes

data:
  build: misc/docker/data
  volumes:
    - .:/app
